"""Research Profile (112.7B) e Interest Engine (112.7F)."""

from .config import (
    InterestChannelWeights,
    InterestEngineConfig,
    InterestEngineLimits,
    InterestPriorityThresholds,
    InterestReasonTemplates,
    InterestReasonType,
    InterestScoringConfig,
)
from .engine import (
    InterestConceptMatch,
    InterestEngine,
    InterestMatchChannel,
    InterestMatchScope,
    InterestPriority,
    InterestResult,
    ResearchLineMatch,
)
from .errors import (
    InterestEngineArithmeticError,
    InterestEngineCompatibilityError,
    InterestEngineConfigError,
    InterestEngineError,
    InterestEngineInputError,
    InterestEngineVersionError,
    InterestEventFingerprintMismatchError,
)
from .loader import ProfileLoadError, load_research_profile
from .models import (
    PreferredSource,
    ResearchConcept,
    ResearchDomain,
    ResearchIdentity,
    ResearchInstrument,
    ResearchLine,
    ResearchProfile,
    ResearchRegion,
    ResolutionRecord,
)

__all__ = [
    "InterestChannelWeights",
    "InterestConceptMatch",
    "InterestEngine",
    "InterestEngineArithmeticError",
    "InterestEngineCompatibilityError",
    "InterestEngineConfig",
    "InterestEngineConfigError",
    "InterestEngineError",
    "InterestEngineInputError",
    "InterestEngineLimits",
    "InterestEngineVersionError",
    "InterestEventFingerprintMismatchError",
    "InterestMatchChannel",
    "InterestMatchScope",
    "InterestPriority",
    "InterestPriorityThresholds",
    "InterestReasonTemplates",
    "InterestReasonType",
    "InterestResult",
    "InterestScoringConfig",
    "PreferredSource",
    "ProfileLoadError",
    "ResearchConcept",
    "ResearchDomain",
    "ResearchIdentity",
    "ResearchInstrument",
    "ResearchLine",
    "ResearchLineMatch",
    "ResearchProfile",
    "ResearchRegion",
    "ResolutionRecord",
    "load_research_profile",
]
