from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID

import pytest

from sentinela.core.models import EpistemicStatus, Event, EventStatus


def volcanic_event(
    *,
    event_id: str = "00000000-0000-0000-0000-000000000001",
    volcano_name: str = "Vulcão Teste",
    volcano_number: str = "999999",
    category: str = "volcano_alert_elevated",
    canonical_group_id: str = "10000000-0000-0000-0000-000000000001",
    occurred_at: datetime | None = datetime(2026, 8, 14, 12, tzinfo=timezone.utc),
    alert_level: str | None = "ADVISORY",
    aviation_color: str | None = "YELLOW",
    observatory: str | None = "Observatório Teste",
    notice_type: str | None = "DU",
    notice_identifier: str = "DOI-USGS-TEST-2026-08-14T12:00:00+00:00",
    official_summary: str | None = "Activity observations are unchanged.",
    gvp_enriched: bool = False,
    volcano_type: str | None = None,
    last_known_eruption: int | None = None,
    source: str = "USGS HANS",
    event_status: EventStatus = EventStatus.OFFICIAL_ALERT,
    scientific_area: str = "volcanology",
    extra_evidence: dict | None = None,
) -> Event:
    evidence = {
        "text": "volcanic_alert",
        "canonical_group_id": canonical_group_id,
        "source": source,
        "product": "HANS/VONA" if source == "USGS HANS" else "VIIRS_SNPP_NRT",
        "volcano_name": volcano_name,
        "volcano_number": volcano_number,
        "alert_level": alert_level,
        "aviation_color_code": aviation_color,
        "observatory": observatory,
        "notice_type": notice_type,
        "notice_identifier": notice_identifier,
        "official_summary": official_summary,
        "gvp_enriched": gvp_enriched,
        "volcano_type": volcano_type,
        "last_known_eruption": last_known_eruption,
        "source_url": "https://example.test/private-source-id",
        "source_event_id": "technical-source-id",
    }
    evidence.update(extra_evidence or {})
    return Event(
        id=UUID(event_id),
        title="Título legado não usado pela editorial",
        summary="Resumo legado com danos, risco e evacuação inventados",
        epistemic_status=EpistemicStatus.CONFIRMED_FACT,
        event_status=event_status,
        category=category,
        source=source,
        scientific_area=scientific_area,
        occurred_at=occurred_at,
        validated_at=occurred_at,
        entities=[{"name": volcano_name, "type": "volcano"}],
        keywords=["volcano"],
        evidence=[evidence],
    )


def _gvp() -> dict:
    return {
        "gvp_enriched": True,
        "volcano_type": "Stratovolcano",
        "last_known_eruption": 2026,
    }


@pytest.fixture
def real_volcanic_events() -> tuple[Event, ...]:
    events = (
        volcanic_event(
            event_id="850ef73c-1889-465a-a4a8-153bfd11aa11",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcano_vona_published",
            canonical_group_id="bcfe7bc2-d7f2-45ed-82af-b73de50c6b41",
            occurred_at=datetime(2026, 8, 12, tzinfo=timezone.utc),
            alert_level="WATCH",
            aviation_color="ORANGE",
            observatory="hvo",
            notice_type="notificação",
            notice_identifier="DOI-USGS-HVO-2026-08-12T21:24:42+00:00",
            official_summary="Precursory low-level eruptive activity began.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=2026,
        ),
        volcanic_event(
            event_id="87ec6cad-8330-4b6c-93ad-28b2af9bbf32",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcano_vona_published",
            canonical_group_id="bcfe7bc2-d7f2-45ed-82af-b73de50c6b41",
            occurred_at=datetime(2026, 8, 13, tzinfo=timezone.utc),
            alert_level="WATCH",
            aviation_color="ORANGE",
            observatory="hvo",
            notice_type="notificação",
            notice_identifier="DOI-USGS-HVO-2026-08-13T00:22:02+00:00",
            official_summary="Episode 53 of the ongoing eruption began at 3:45 p.m.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=2026,
        ),
        volcanic_event(
            event_id="144e7612-9138-4c5f-b821-b73804c5b29b",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcano_vona_published",
            canonical_group_id="bcfe7bc2-d7f2-45ed-82af-b73de50c6b41",
            occurred_at=datetime(2026, 8, 13, tzinfo=timezone.utc),
            alert_level="WATCH",
            aviation_color="ORANGE",
            observatory="hvo",
            notice_type="notificação",
            notice_identifier="DOI-USGS-HVO-2026-08-13T02:46:38+00:00",
            official_summary="Episode 53 of the ongoing eruption continues.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=2026,
        ),
        volcanic_event(
            event_id="f687fd9e-afd8-4dd8-a6dc-bc96d54977db",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcano_vona_published",
            canonical_group_id="bcfe7bc2-d7f2-45ed-82af-b73de50c6b41",
            occurred_at=datetime(2026, 8, 13, tzinfo=timezone.utc),
            alert_level="ADVISORY",
            aviation_color="YELLOW",
            observatory="hvo",
            notice_type="notificação",
            notice_identifier="DOI-USGS-HVO-2026-08-13T04:16:32+00:00",
            official_summary="Episode 53 of the ongoing eruption ended abruptly.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=2026,
        ),
        volcanic_event(
            event_id="42cc1d3c-4bec-4257-9e6e-d71a00a0da5d",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcano_notice_published",
            canonical_group_id="514a99ee-766a-4215-94a1-81f303a9e055",
            occurred_at=datetime(2026, 8, 13, 11, 56, 54, tzinfo=timezone.utc),
            alert_level="ADVISORY",
            aviation_color="YELLOW",
            observatory="Hawaiian Volcano Observatory",
            notice_type="Status Report",
            official_summary="Episode 53 of the ongoing eruption began and ended at 1:23 a.m.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=2026,
        ),
        volcanic_event(
            event_id="888063d6-138f-4363-b371-cf96390e922d",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcano_alert_elevated",
            canonical_group_id="ff5f5144-0fce-488d-be8c-184254b34603",
            occurred_at=datetime(2026, 8, 13, 19, 19, 33, tzinfo=timezone.utc),
            alert_level="ADVISORY",
            aviation_color="YELLOW",
            observatory="Hawaiian Volcano Observatory",
            official_summary="Kilauea is not erupting; the summit eruption is paused.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=2026,
        ),
        volcanic_event(
            event_id="47ca5ac2-4809-4933-8649-1f32a02adbf8",
            volcano_name="Kama'ehuakanaloa",
            volcano_number="332000",
            category="volcano_notice_published",
            canonical_group_id="ca071e51-a207-428d-b06e-9e3b69f015da",
            occurred_at=datetime(2026, 8, 12, 4, 42, 14, tzinfo=timezone.utc),
            alert_level="UNASSIGNED",
            aviation_color="UNASSIGNED",
            observatory="Hawaiian Volcano Observatory",
            notice_type="Information Statement",
            official_summary="Magnitude-5.2 earthquake beneath Kama'ehuakanaloa.",
            gvp_enriched=True,
            volcano_type="Shield",
            last_known_eruption=1996,
        ),
        volcanic_event(
            event_id="54507752-058e-4394-bbd7-ac2d87002ffe",
            volcano_name="Shishaldin",
            volcano_number="311360",
            canonical_group_id="8d18100d-285f-4a6a-b3f9-bbfde08df543",
            occurred_at=datetime(2026, 8, 13, 21, 47, 40, tzinfo=timezone.utc),
            observatory="Alaska Volcano Observatory",
            official_summary="Seismic and infrasound events continue.",
            **_gvp(),
        ),
        volcanic_event(
            event_id="a687a35f-b716-42a2-b79f-f6b663e8a3f8",
            volcano_name="Great Sitkin",
            volcano_number="311120",
            canonical_group_id="a157d649-e77c-4421-843c-f1eec3caeb12",
            occurred_at=datetime(2026, 8, 13, 21, 47, 40, tzinfo=timezone.utc),
            alert_level="WATCH",
            aviation_color="ORANGE",
            observatory="Alaska Volcano Observatory",
            official_summary="Slow eruption of lava within the summit crater continues.",
            **_gvp(),
        ),
        volcanic_event(
            event_id="c68bc69f-117f-4d03-895a-806cf33fa7fa",
            volcano_name="Kupreanof",
            volcano_number="312060",
            canonical_group_id="b6064403-f17f-475f-90e6-cf819064d4ac",
            occurred_at=datetime(2026, 8, 13, 21, 47, 40, tzinfo=timezone.utc),
            observatory="Alaska Volcano Observatory",
            official_summary="Low-level seismic activity continued over the past day.",
            gvp_enriched=True,
            volcano_type="Stratovolcano",
        ),
        volcanic_event(
            event_id="e65163ab-18c7-40d0-bbbb-48ed1e186719",
            volcano_name="Ahyi Seamount",
            volcano_number="284141",
            canonical_group_id="d815f3e8-f148-4277-a055-bf8df19c2e9b",
            occurred_at=datetime(2026, 8, 14, 0, 2, 20, tzinfo=timezone.utc),
            observatory="Northern Mariana Islands",
            notice_type="WU",
            official_summary="No signs of unrest in satellite images or distal geophysical data this past week.",
            **_gvp(),
        ),
        volcanic_event(
            event_id="6d1e227b-98cd-42fe-b921-0a417116a48e",
            volcano_name="Kilauea",
            volcano_number="332010",
            category="volcanic_thermal_anomaly_candidate",
            canonical_group_id="f94bc6d6-85e7-439d-983f-dc57335ce7ce",
            occurred_at=datetime(2026, 8, 14, 13, 59, tzinfo=timezone.utc),
            alert_level=None,
            aviation_color=None,
            observatory=None,
            notice_type=None,
            official_summary=None,
            source="NASA FIRMS",
            event_status=EventStatus.OBSERVED_FACT,
            extra_evidence={
                "hotspot_count": 128,
                "distance_to_volcano_km": 0.3619820921097211,
                "earliest_acquisition": "2026-08-14T00:03:00+00:00",
                "latest_acquisition": "2026-08-14T13:59:00+00:00",
                "sensors": ["MODIS_NRT", "VIIRS_NOAA20_NRT", "VIIRS_SNPP_NRT"],
            },
        ),
    )
    return tuple(reversed(events))
